### ISSUE TITLE
Collapsible list buttons are wider than actual panel

### ISSUE THREAD

**Issue by Swagmoneydre69** [rcos/CSCI-4470-OpenSource#78] opened 2023-04-20 22:22 UTC
If you click on a button in the collapsible list on the modules/assignments/resources pages, the buttons themselves are wider than the collapsible panels that drop down.

<img width="678" alt="image" src="https://user-images.githubusercontent.com/5789868/233499787-d1e13f27-78c6-4662-93a6-e727ec16bb2b.png">

**Comment by nazime1** [comment] 2023-08-04 19:53
As of [this commit](https://github.com/rcos/CSCI-4470-OpenSource/commit/e8999bc988d3c771dafa713c8a4accdcf4eefa9d), the issue is fixed by using the react-collapsible feature.

**Closed by nazime1** 2023-08-04 19:53 UTC
Labels: bug
